Import Modules

In [41]:
import pandas as pd
import numpy as np

### Create Custom Data

In [42]:
# Create a dictionary with sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Age': [24, 27, 22, 32, 29, 45, 30, np.nan, 25, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'New York', 'Chicago', 'Los Angeles', 'Houston', 'Phoenix'],
    'Score': [88, 92, 75, np.nan, 85, 90, 78, 83, 91, 70],
    'Status': ['Active', 'Inactive', 'Active', 'Active', 'Inactive', 'Active', 'Active', 'Inactive', 'Active', 'Active']
}

# Create the DataFrame
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df)

Original DataFrame:

      Name   Age         City  Score    Status
0    Alice  24.0     New York   88.0    Active
1      Bob  27.0  Los Angeles   92.0  Inactive
2  Charlie  22.0      Chicago   75.0    Active
3    David  32.0      Houston    NaN    Active
4      Eve  29.0      Phoenix   85.0  Inactive
5    Frank  45.0     New York   90.0    Active
6    Grace  30.0      Chicago   78.0    Active
7    Heidi   NaN  Los Angeles   83.0  Inactive
8     Ivan  25.0      Houston   91.0    Active
9     Judy  28.0      Phoenix   70.0    Active

## Data Cleaning Demonstration

#### 1. Handling Missing Values: `fillna()`
Replacing `NaN` (Not a Number) values with a specified value (e.g., 0, mean, or a specific string). This can be done directly on the DataFrame or on a specific column.

**Syntax:** `df.fillna(value, inplace=True)` or `df['column'].fillna(value, inplace=True)`

In [43]:
# Create a copy to demonstrate inplace modification without affecting the original 'df'
df_demo = df.copy()

# Fill missing 'Age' values with the mean age
df_demo['Age'] = df_demo['Age'].fillna(df_demo['Age'].mean())

# Fill missing 'Score' values with 0
df_demo['Score'] = df_demo['Score'].fillna(0)

print("DataFrame after filling missing 'Age' with mean and 'Score' with 0 (using reassignment):")
display(df_demo)

DataFrame after filling missing 'Age' with mean and 'Score' with 0 (using reassignment):

      Name        Age         City  Score    Status
0    Alice  24.000000     New York   88.0    Active
1      Bob  27.000000  Los Angeles   92.0  Inactive
2  Charlie  22.000000      Chicago   75.0    Active
3    David  32.000000      Houston    0.0    Active
4      Eve  29.000000      Phoenix   85.0  Inactive
5    Frank  45.000000     New York   90.0    Active
6    Grace  30.000000      Chicago   78.0    Active
7    Heidi  29.111111  Los Angeles   83.0  Inactive
8     Ivan  25.000000      Houston   91.0    Active
9     Judy  28.000000      Phoenix   70.0    Active

#### Additional Missing Value Handling: `ffill()` and `bfill()`
These methods are used to propagate the last valid observation forward (`ffill`) or next valid observation backward (`bfill`) to fill `NaN` values.

**Syntax:** `df.ffill(inplace=True)` or `df.bfill(inplace=True)`

In [44]:
# Create a copy to demonstrate ffill (forward fill)
df_ffill = df.copy()

# Sort by 'Age' and 'Score' for a more meaningful ffill
df_ffill_sorted = df_ffill.sort_values(by=['Age', 'Score']).reset_index(drop=True)
print("DataFrame sorted for ffill demonstration:")
display(df_ffill_sorted)

# Forward fill missing values in 'Age' and 'Score' columns
df_ffill_sorted['Age'] = df_ffill_sorted['Age'].ffill()
df_ffill_sorted['Score'] = df_ffill_sorted['Score'].ffill()

print("\nDataFrame after forward filling missing values (ffill using reassignment):")
display(df_ffill_sorted)

DataFrame sorted for ffill demonstration:

      Name   Age         City  Score    Status
0  Charlie  22.0      Chicago   75.0    Active
1    Alice  24.0     New York   88.0    Active
2     Ivan  25.0      Houston   91.0    Active
3      Bob  27.0  Los Angeles   92.0  Inactive
4     Judy  28.0      Phoenix   70.0    Active
5      Eve  29.0      Phoenix   85.0  Inactive
6    Grace  30.0      Chicago   78.0    Active
7    David  32.0      Houston    NaN    Active
8    Frank  45.0     New York   90.0    Active
9    Heidi   NaN  Los Angeles   83.0  Inactive

DataFrame after forward filling missing values (ffill using reassignment):

      Name   Age         City  Score    Status
0  Charlie  22.0      Chicago   75.0    Active
1    Alice  24.0     New York   88.0    Active
2     Ivan  25.0      Houston   91.0    Active
3      Bob  27.0  Los Angeles   92.0  Inactive
4     Judy  28.0      Phoenix   70.0    Active
5      Eve  29.0      Phoenix   85.0  Inactive
6    Grace  30.0      Chicago   78.0    Active
7    David  32.0      Houston   78.0    Active
8    Frank  45.0     New York   90.0    Active
9    Heidi  45.0  Los Angeles   83.0  Inactive

In [45]:
# Create a copy to demonstrate bfill (backward fill)
df_bfill = df.copy()

# Sort by 'Age' and 'Score' for a more meaningful bfill
df_bfill_sorted = df_bfill.sort_values(by=['Age', 'Score'], ascending=False).reset_index(drop=True)
print("DataFrame sorted (desc) for bfill demonstration:")
display(df_bfill_sorted)

# Backward fill missing values in 'Age' and 'Score' columns
df_bfill_sorted['Age'] = df_bfill_sorted['Age'].bfill()
df_bfill_sorted['Score'] = df_bfill_sorted['Score'].bfill()

print("\nDataFrame after backward filling missing values (bfill using reassignment):")
display(df_bfill_sorted)

DataFrame sorted (desc) for bfill demonstration:

      Name   Age         City  Score    Status
0    Frank  45.0     New York   90.0    Active
1    David  32.0      Houston    NaN    Active
2    Grace  30.0      Chicago   78.0    Active
3      Eve  29.0      Phoenix   85.0  Inactive
4     Judy  28.0      Phoenix   70.0    Active
5      Bob  27.0  Los Angeles   92.0  Inactive
6     Ivan  25.0      Houston   91.0    Active
7    Alice  24.0     New York   88.0    Active
8  Charlie  22.0      Chicago   75.0    Active
9    Heidi   NaN  Los Angeles   83.0  Inactive

DataFrame after backward filling missing values (bfill using reassignment):

      Name   Age         City  Score    Status
0    Frank  45.0     New York   90.0    Active
1    David  32.0      Houston   78.0    Active
2    Grace  30.0      Chicago   78.0    Active
3      Eve  29.0      Phoenix   85.0  Inactive
4     Judy  28.0      Phoenix   70.0    Active
5      Bob  27.0  Los Angeles   92.0  Inactive
6     Ivan  25.0      Houston   91.0    Active
7    Alice  24.0     New York   88.0    Active
8  Charlie  22.0      Chicago   75.0    Active
9    Heidi   NaN  Los Angeles   83.0  Inactive

#### Identifying Missing Values: `isna()` and `isnull()`
Both `df.isna()` and `df.isnull()` are aliases and return a boolean DataFrame of the same shape as the original DataFrame, indicating `True` where values are `NaN` (or `None` for object types) and `False` otherwise. They are very useful for identifying and counting missing values.

**Syntax:** `df.isna()` or `df.isnull()`

In [46]:
# Identify missing values using isna()
print("Boolean DataFrame indicating missing values (using isna()):")
display(df.isna())

# Count missing values per column using isna().sum()
print("\nNumber of missing values per column (using isna().sum()):")
display(df.isna().sum())

# Identify missing values using isnull() (alias for isna())
print("\nBoolean DataFrame indicating missing values (using isnull()):")
display(df.isnull())

# Count missing values per row using isnull().sum(axis=1)
print("\nNumber of missing values per row (using isnull().sum(axis=1)):")
display(df.isnull().sum(axis=1))

Boolean DataFrame indicating missing values (using isna()):

    Name    Age   City  Score  Status
0  False  False  False  False   False
1  False  False  False  False   False
2  False  False  False  False   False
3  False  False  False   True   False
4  False  False  False  False   False
5  False  False  False  False   False
6  False  False  False  False   False
7  False   True  False  False   False
8  False  False  False  False   False
9  False  False  False  False   False

Number of missing values per column (using isna().sum()):

Name      0
Age       1
City      0
Score     1
Status    0
dtype: int64

Boolean DataFrame indicating missing values (using isnull()):

    Name    Age   City  Score  Status
0  False  False  False  False   False
1  False  False  False  False   False
2  False  False  False  False   False
3  False  False  False   True   False
4  False  False  False  False   False
5  False  False  False  False   False
6  False  False  False  False   False
7  False   True  False  False   False
8  False  False  False  False   False
9  False  False  False  False   False

Number of missing values per row (using isnull().sum(axis=1)):

0    0
1    0
2    0
3    1
4    0
5    0
6    0
7    1
8    0
9    0
dtype: int64

#### 2. Handling Missing Values: `dropna()`
Removing rows or columns that contain missing values.

**Syntax:** `df.dropna(axis=0, how='any', inplace=False)`
*   `axis`: This parameter determines whether to drop rows or columns.
    *   `axis=0` (default): Refers to rows. The operation is applied row-wise.
    *   `axis=1`: Refers to columns. The operation is applied column-wise.
*   `how`: 'any' (drop if any NaN is present) or 'all' (drop if all values are NaN).

In [47]:
# Create a copy to demonstrate different dropna scenarios without altering the original df
df_demo = df.copy()

# Drop rows with any missing values (axis=0, how='any' are defaults)
print("DataFrame after dropping rows with any missing values:")
df_rows_any = df_demo.dropna(axis=0, how='any')
display(df_rows_any)

# To demonstrate how='all', let's create a row that is entirely NaN
df_nan_row = df.copy()
df_nan_row.loc[len(df_nan_row)] = [np.nan, np.nan, np.nan, np.nan, np.nan] # Add a completely NaN row
print("\nDataFrame with an all-NaN row:")
display(df_nan_row)

print("DataFrame after dropping rows where ALL values are missing (how='all'):")
df_rows_all = df_nan_row.dropna(axis=0, how='all')
display(df_rows_all)

# Drop columns with any missing values
print("\nDataFrame after dropping columns with any missing values:")
df_cols_any = df_demo.dropna(axis=1, how='any')
display(df_cols_any)

# Demonstrate inplace=True for dropping rows with any missing values
df_inplace_demo = df.copy()
print("\nOriginal DataFrame for inplace dropna demo:")
display(df_inplace_demo)
df_inplace_demo.dropna(inplace=True)
print("DataFrame after dropping rows with any missing values (inplace=True):")
display(df_inplace_demo)

DataFrame after dropping rows with any missing values:

      Name   Age         City  Score    Status
0    Alice  24.0     New York   88.0    Active
1      Bob  27.0  Los Angeles   92.0  Inactive
2  Charlie  22.0      Chicago   75.0    Active
4      Eve  29.0      Phoenix   85.0  Inactive
5    Frank  45.0     New York   90.0    Active
6    Grace  30.0      Chicago   78.0    Active
8     Ivan  25.0      Houston   91.0    Active
9     Judy  28.0      Phoenix   70.0    Active

DataFrame with an all-NaN row:

       Name   Age         City  Score    Status
0     Alice  24.0     New York   88.0    Active
1       Bob  27.0  Los Angeles   92.0  Inactive
2   Charlie  22.0      Chicago   75.0    Active
3     David  32.0      Houston    NaN    Active
4       Eve  29.0      Phoenix   85.0  Inactive
5     Frank  45.0     New York   90.0    Active
6     Grace  30.0      Chicago   78.0    Active
7     Heidi   NaN  Los Angeles   83.0  Inactive
8      Ivan  25.0      Houston   91.0    Active
9      Judy  28.0      Phoenix   70.0    Active
10      NaN   NaN          NaN    NaN       NaN

DataFrame after dropping rows where ALL values are missing (how='all'):

      Name   Age         City  Score    Status
0    Alice  24.0     New York   88.0    Active
1      Bob  27.0  Los Angeles   92.0  Inactive
2  Charlie  22.0      Chicago   75.0    Active
3    David  32.0      Houston    NaN    Active
4      Eve  29.0      Phoenix   85.0  Inactive
5    Frank  45.0     New York   90.0    Active
6    Grace  30.0      Chicago   78.0    Active
7    Heidi   NaN  Los Angeles   83.0  Inactive
8     Ivan  25.0      Houston   91.0    Active
9     Judy  28.0      Phoenix   70.0    Active

DataFrame after dropping columns with any missing values:

      Name         City    Status
0    Alice     New York    Active
1      Bob  Los Angeles  Inactive
2  Charlie      Chicago    Active
3    David      Houston    Active
4      Eve      Phoenix  Inactive
5    Frank     New York    Active
6    Grace      Chicago    Active
7    Heidi  Los Angeles  Inactive
8     Ivan      Houston    Active
9     Judy      Phoenix    Active

Original DataFrame for inplace dropna demo:

      Name   Age         City  Score    Status
0    Alice  24.0     New York   88.0    Active
1      Bob  27.0  Los Angeles   92.0  Inactive
2  Charlie  22.0      Chicago   75.0    Active
3    David  32.0      Houston    NaN    Active
4      Eve  29.0      Phoenix   85.0  Inactive
5    Frank  45.0     New York   90.0    Active
6    Grace  30.0      Chicago   78.0    Active
7    Heidi   NaN  Los Angeles   83.0  Inactive
8     Ivan  25.0      Houston   91.0    Active
9     Judy  28.0      Phoenix   70.0    Active

DataFrame after dropping rows with any missing values (inplace=True):

      Name   Age         City  Score    Status
0    Alice  24.0     New York   88.0    Active
1      Bob  27.0  Los Angeles   92.0  Inactive
2  Charlie  22.0      Chicago   75.0    Active
4      Eve  29.0      Phoenix   85.0  Inactive
5    Frank  45.0     New York   90.0    Active
6    Grace  30.0      Chicago   78.0    Active
8     Ivan  25.0      Houston   91.0    Active
9     Judy  28.0      Phoenix   70.0    Active

#### 3. Data Type Conversion: `astype()`
Changing the data type of a column.

**Syntax:** `df['column'].astype(dtype)`

In [48]:
# Convert 'Age' column to integer type (after filling NaN if any, or using errors='ignore' for safety)
df_converted = df.copy()
df_converted['Age'] = df_converted['Age'].fillna(df_converted['Age'].mean()).astype(int)

print("DataFrame with 'Age' column converted to integer type:\n")
display(df_converted.info())

DataFrame with 'Age' column converted to integer type:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Score   9 non-null      float64
 4   Status  10 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 532.0+ bytes

None

#### 3.1 Clamping Values: `clip()`

The `clip()` function is used to trim values at input thresholds. Values outside the interval `[lower, upper]` are clipped to the interval edges. That is, values smaller than `lower` become `lower`, and values larger than `upper` become `upper`.

**Syntax:** `df['column'].clip(lower=min_value, upper=max_value)`

In [53]:
# Create a copy to demonstrate clip()
df_clip = df.copy()

# Let's say we want to ensure 'Age' is between 20 and 40, and 'Score' is between 60 and 100.
# First, we need to fill NaN values in 'Score' and 'Age' before clipping, as clip doesn't handle NaN directly.
df_clip['Age'] = df_clip['Age'].fillna(df_clip['Age'].mean())
df_clip['Score'] = df_clip['Score'].fillna(df_clip['Score'].mean())

print("Original DataFrame (after NaN filled) for clip demonstration:")
display(df_clip)

# Clip 'Age' values to be between 20 and 40
df_clip['Age'] = df_clip['Age'].clip(lower=20, upper=40)

# Clip 'Score' values to be between 60 and 100
df_clip['Score'] = df_clip['Score'].clip(lower=60, upper=100)

print("\nDataFrame after clipping 'Age' (20-40) and 'Score' (60-100):")
display(df_clip)

Original DataFrame (after NaN filled) for clip demonstration:

      Name        Age         City      Score    Status
0    Alice  24.000000     New York  88.000000    Active
1      Bob  27.000000  Los Angeles  92.000000  Inactive
2  Charlie  22.000000      Chicago  75.000000    Active
3    David  32.000000      Houston  83.555556    Active
4      Eve  29.000000      Phoenix  85.000000  Inactive
5    Frank  45.000000     New York  90.000000    Active
6    Grace  30.000000      Chicago  78.000000    Active
7    Heidi  29.111111  Los Angeles  83.000000  Inactive
8     Ivan  25.000000      Houston  91.000000    Active
9     Judy  28.000000      Phoenix  70.000000    Active

DataFrame after clipping 'Age' (20-40) and 'Score' (60-100):

      Name        Age         City      Score    Status
0    Alice  24.000000     New York  88.000000    Active
1      Bob  27.000000  Los Angeles  92.000000  Inactive
2  Charlie  22.000000      Chicago  75.000000    Active
3    David  32.000000      Houston  83.555556    Active
4      Eve  29.000000      Phoenix  85.000000  Inactive
5    Frank  40.000000     New York  90.000000    Active
6    Grace  30.000000      Chicago  78.000000    Active
7    Heidi  29.111111  Los Angeles  83.000000  Inactive
8     Ivan  25.000000      Houston  91.000000    Active
9     Judy  28.000000      Phoenix  70.000000    Active

#### 4. Handling Duplicates

Identifying Duplicates: `duplicated()`
This function returns a Boolean Series indicating whether each row is a duplicate of a previous row. It's useful for inspecting duplicates before dropping them.

**Syntax:** `df.duplicated(subset=None, keep='first')`
*   `subset`: Column(s) to consider for identifying duplicates.
*   `keep`: 'first' (mark all but the first occurrence as `True`), 'last' (mark all but the last as `True`), or `False` (mark all duplicates as `True`).

In [49]:
# Create a DataFrame with some duplicate rows for demonstration
df_dup = pd.DataFrame({
    'ColA': [1, 2, 1, 3, 2],
    'ColB': ['X', 'Y', 'X', 'Z', 'Y']
})
print("Original DataFrame with duplicates:")
display(df_dup)

# Using the DataFrame with duplicates from the previous example
print("Original DataFrame with duplicates:")
display(df_dup)

# Identify duplicate rows (default: marks all but the first occurrence as True)
dup_rows_default = df_dup.duplicated()
print("\nBoolean Series identifying duplicate rows (default - marks all but first as True):")
display(dup_rows_default)

# Identify all occurrences of duplicates (marks all duplicate rows as True)
dup_rows_all = df_dup.duplicated(keep=False)
print("\nBoolean Series identifying ALL duplicate rows (keep=False):")
display(dup_rows_all)

# Identify duplicates based on 'ColA' only
dup_col_a = df_dup.duplicated(subset=['ColA'])
print("\nBoolean Series identifying duplicate rows based on 'ColA':")
display(dup_col_a)

Original DataFrame with duplicates:

   ColA ColB
0     1    X
1     2    Y
2     1    X
3     3    Z
4     2    Y

Original DataFrame with duplicates:

   ColA ColB
0     1    X
1     2    Y
2     1    X
3     3    Z
4     2    Y

Boolean Series identifying duplicate rows (default - marks all but first as True):

0    False
1    False
2     True
3    False
4     True
dtype: bool

Boolean Series identifying ALL duplicate rows (keep=False):

0     True
1     True
2     True
3    False
4     True
dtype: bool

Boolean Series identifying duplicate rows based on 'ColA':

0    False
1    False
2     True
3    False
4     True
dtype: bool

Removing Duplicates: `drop_duplicates()`
Eliminating duplicate rows from the DataFrame.

**Syntax:** `df.drop_duplicates(subset=None, keep='first', inplace=False)`
*   `subset`: Column(s) to consider for identifying duplicates.
*   `keep`:
    *   `'first'` (default): Keep the first occurrence, drop duplicates.
    *   `'last'`: Keep the last occurrence, drop duplicates.
    *   `False`: Drop all occurrences where a row is duplicated.
*   `inplace`: If `True`, modifies the DataFrame directly.

In [50]:
# Create a DataFrame with some duplicate rows for demonstration
df_extended_dup = pd.DataFrame({
    'ColA': [1, 2, 1, 3, 2, 1],
    'ColB': ['X', 'Y', 'X', 'Z', 'Y', 'X']
})
print("Original DataFrame with duplicates:")
display(df_extended_dup)

# Drop duplicate rows (keeps the first occurrence by default, or explicitly with keep='first')
df_no_dup_first = df_extended_dup.drop_duplicates(keep='first')
print("\nDataFrame after dropping duplicates (keep='first' - default behavior):")
display(df_no_dup_first)

# Drop duplicate rows based on 'ColA' and keep the last occurrence
df_no_dup_subset_last = df_extended_dup.drop_duplicates(subset=['ColA'], keep='last')
print("\nDataFrame after dropping duplicates based on 'ColA', keeping the last:")
display(df_no_dup_subset_last)

# Drop all occurrences of duplicate rows (keep=False)
df_no_dup_all = df_extended_dup.drop_duplicates(keep=False)
print("\nDataFrame after dropping ALL occurrences of duplicate rows (keep=False):")
display(df_no_dup_all)

# Demonstrate inplace=True for dropping duplicates (keeping first as default)
df_inplace_dup = df_extended_dup.copy()
print("\nOriginal DataFrame for inplace drop_duplicates demo:")
display(df_inplace_dup)
def_1 = df_inplace_dup.drop_duplicates(inplace=False)
print("DataFrame after dropping duplicates (inplace=True, keep='first' implicit):")
display(df_inplace_dup)
print(def_1)

Original DataFrame with duplicates:

   ColA ColB
0     1    X
1     2    Y
2     1    X
3     3    Z
4     2    Y
5     1    X

DataFrame after dropping duplicates (keep='first' - default behavior):

   ColA ColB
0     1    X
1     2    Y
3     3    Z

DataFrame after dropping duplicates based on 'ColA', keeping the last:

   ColA ColB
3     3    Z
4     2    Y
5     1    X

DataFrame after dropping ALL occurrences of duplicate rows (keep=False):

   ColA ColB
3     3    Z

Original DataFrame for inplace drop_duplicates demo:

   ColA ColB
0     1    X
1     2    Y
2     1    X
3     3    Z
4     2    Y
5     1    X

DataFrame after dropping duplicates (inplace=True, keep='first' implicit):

   ColA ColB
0     1    X
1     2    Y
2     1    X
3     3    Z
4     2    Y
5     1    X

   ColA ColB
0     1    X
1     2    Y
3     3    Z

#### 5. Renaming Columns: `rename()`
Changing the names of columns or index labels.

**Syntax:** `df.rename(columns={'old_name': 'new_name'}, inplace=False)`

In [51]:
# Rename 'Score' to 'Exam_Score' directly on a copy of the DataFrame
df_renamed = df.copy()
df_renamed.rename(columns={'Score': 'Exam_Score'}, inplace=True)

print("DataFrame after renaming 'Score' to 'Exam_Score' (using inplace=True):")
display(df_renamed)

DataFrame after renaming 'Score' to 'Exam_Score' (using inplace=True):

      Name   Age         City  Exam_Score    Status
0    Alice  24.0     New York        88.0    Active
1      Bob  27.0  Los Angeles        92.0  Inactive
2  Charlie  22.0      Chicago        75.0    Active
3    David  32.0      Houston         NaN    Active
4      Eve  29.0      Phoenix        85.0  Inactive
5    Frank  45.0     New York        90.0    Active
6    Grace  30.0      Chicago        78.0    Active
7    Heidi   NaN  Los Angeles        83.0  Inactive
8     Ivan  25.0      Houston        91.0    Active
9     Judy  28.0      Phoenix        70.0    Active

#### 6. Applying a Function to a Column: `apply()`
Applying a custom function to a column's values.

**Syntax:** `df['column'].apply(function)`

In [52]:
# Create a new column 'Age_Group' based on 'Age'
df_apply = df.copy()

def get_age_group(age):
    if pd.isna(age):
        return 'Unknown'
    elif age < 30:
        return 'Young'
    else:
        return 'Adult'

df_apply['Age_Group'] = df_apply['Age'].apply(get_age_group)

print("DataFrame with new 'Age_Group' column:")
display(df_apply)

DataFrame with new 'Age_Group' column:

      Name   Age         City  Score    Status Age_Group
0    Alice  24.0     New York   88.0    Active     Young
1      Bob  27.0  Los Angeles   92.0  Inactive     Young
2  Charlie  22.0      Chicago   75.0    Active     Young
3    David  32.0      Houston    NaN    Active     Adult
4      Eve  29.0      Phoenix   85.0  Inactive     Young
5    Frank  45.0     New York   90.0    Active     Adult
6    Grace  30.0      Chicago   78.0    Active     Adult
7    Heidi   NaN  Los Angeles   83.0  Inactive   Unknown
8     Ivan  25.0      Houston   91.0    Active     Young
9     Judy  28.0      Phoenix   70.0    Active     Young